package guru.sfg.beer.order.service.domain;

public enum BeerOrderStatusEnum {
    NEW, VALIDATION_PENDING, VALIDATED, VALIDATED_EXCEPTION, ALLOCATED, ALLOCATION_EXCEPTION, PENDING_INVENTORY,
    PICKED_UP, DELIVERED, DELIVERY_EXCEPTION;
}
